export const themeSettings = {
	// Set this to the theme id you want to use as the starter default.
	defaultThemeId: "precision-orange",
	// Disable this for production sites that should not expose theme choices.
	showThemeSwitcher: false,
	// Disable this with showThemeSwitcher when you want the configured default to always win.
	persistUserSelection: true,
	storageKey: "theme_id",
	cookieName: "theme_id",
};

export const defaultThemeId = themeSettings.defaultThemeId;
export const showThemeSwitcher = themeSettings.showThemeSwitcher;

export const themes = [
	{
		id: "retro-blue",
		name: "Retro Blue",
		description:
			"A warm editorial palette with blue headings, gold highlights, and calm slate neutrals.",
		source: "Default palette",
		designDoc: "docs/DESIGN/retro-blue.md",
		details: {
			atmosphere:
				"Warm editorial canvas with confident blue headings, gold highlights, and calm slate neutrals.",
			bestFor: ["Starter sites", "Editorial product pages", "Documentation"],
			colorRoles: [
				{ name: "Editorial Blue", value: "#2d6dc3", role: "Headings, links, and primary actions" },
				{ name: "Gold Highlight", value: "#fad13b", role: "Badges and secondary emphasis" },
				{ name: "Warm Canvas", value: "#fdfaf5", role: "Light page background" },
			],
			guidance: [
				"Keep blue as the main signal for navigation, headings, and calls to action.",
				"Use gold as a small highlight rather than a large surface color.",
				"Preserve the warm canvas so the theme feels editorial instead of corporate.",
			],
		},
		swatches: ["#2d6dc3", "#8fb9ff", "#fad13b", "#fdfaf5", "#0b1220"],
		lightSwatches: ["#2d6dc3", "#0066ff", "#8fb9ff", "#fad13b", "#fdfaf5", "#ffffff"],
		darkSwatches: ["#3884eb", "#8fb9ff", "#bcd8ff", "#faeb75", "#0b1220", "#0f1b2d"],
		tokens: {
			light: {
				"--color-primary": "#2d6dc3",
				"--color-primary-rgb": "45, 109, 195",
				"--color-primary-strong": "#0066ff",
				"--color-primary-dark": "#2d6dc3",
				"--color-primary-light": "#8fb9ff",
				"--color-primary-light-dark": "#bcd8ff",
				"--color-primary-lighter": "#6da7ff",
				"--color-primary-bg": "var(--color-bg-primary-light)",
				"--color-primary-bg-light": "var(--color-bg-secondary)",
				"--color-accent": "#fad13b",
				"--color-accent-rgb": "250, 209, 59",
				"--color-accent-light": "#faeb75",
				"--color-bg-primary": "#fdfaf5",
				"--color-bg-secondary": "#ffffff",
				"--color-bg-primary-light": "#faf9f5",
				"--color-bg-primary-deep": "#fefcf4",
				"--color-bg-primary-dark": "#0b1220",
				"--color-bg-secondary-dark": "#0f1b2d",
				"--color-text-primary": "#2d6dc3",
				"--color-text-secondary": "#3f4a5a",
				"--color-text-tertiary": "#7a6550",
				"--color-text-primary-dark": "#3884eb",
				"--color-text-secondary-dark": "#c5cedb",
				"--color-text-tertiary-dark": "#9bb3d7",
				"--color-btn-primary": "#2d6dc3",
				"--color-btn-primary-hover": "#0066ff",
				"--color-btn-primary-dark": "#2871e9",
				"--color-btn-primary-dark-hover": "#2d6dc3",
				"--color-btn-primary-text": "#ffffff",
			},
			dark: {
				"--color-primary": "#3884eb",
				"--color-primary-rgb": "56, 132, 235",
				"--color-primary-strong": "#8fb9ff",
				"--color-primary-light": "#bcd8ff",
				"--color-primary-dark": "#3884eb",
				"--color-primary-light-dark": "#3884eb",
				"--color-primary-lighter": "#8fb9ff",
				"--color-primary-bg": "rgba(56, 132, 235, 0.15)",
				"--color-primary-bg-light": "rgba(56, 132, 235, 0.05)",
				"--color-accent": "#faeb75",
				"--color-accent-rgb": "250, 235, 117",
				"--color-accent-light": "#faeb75",
				"--color-bg-primary": "#0b1220",
				"--color-bg-secondary": "#0f1b2d",
				"--color-bg-primary-light": "#101b2b",
				"--color-bg-primary-deep": "#08101d",
				"--color-bg-primary-dark": "#0b1220",
				"--color-bg-secondary-dark": "#0f1b2d",
				"--color-text-primary": "#3884eb",
				"--color-text-secondary": "#c5cedb",
				"--color-text-tertiary": "#9bb3d7",
				"--color-text-primary-dark": "#3884eb",
				"--color-text-secondary-dark": "#c5cedb",
				"--color-text-tertiary-dark": "#9bb3d7",
				"--color-btn-primary": "#2871e9",
				"--color-btn-primary-hover": "#3884eb",
				"--color-btn-primary-dark": "#2871e9",
				"--color-btn-primary-dark-hover": "#3884eb",
				"--color-btn-primary-text": "#ffffff",
			},
		},
	},
	{
		id: "minimal-mono",
		name: "Minimal Mono",
		description:
			"A restrained black, white, and warm gray theme with crisp type contrast and almost no saturated color.",
		source: "Monochrome palette",
		designDoc: "docs/DESIGN/minimal-mono.md",
		details: {
			atmosphere:
				"Restrained monochrome with warm grays, crisp type contrast, and almost no saturated color.",
			bestFor: ["Editorial sites", "Portfolios", "Documentation"],
			colorRoles: [
				{ name: "Ink", value: "#1a1a1a", role: "Text, headings, and primary controls" },
				{ name: "Warm Gray", value: "#f5f3f1", role: "Soft surfaces and quiet accents" },
				{ name: "Paper", value: "#fdfcfc", role: "Light page canvas" },
			],
			guidance: [
				"Do not introduce new saturated accents; the restraint is the feature.",
				"Use gray hierarchy for emphasis instead of colored labels.",
				"Keep the theme quiet enough for long-form reading.",
			],
		},
		swatches: ["#1a1a1a", "#777169", "#e5e5e5", "#fdfcfc", "#f5f3f1"],
		lightSwatches: ["#1a1a1a", "#333333", "#b1b0b0", "#f5f3f1", "#fdfcfc", "#ffffff"],
		darkSwatches: ["#f4f4f2", "#ffffff", "#d2d2cf", "#2a2927", "#11110f", "#1a1917"],
		tokens: {
			light: {
				"--color-primary": "#1a1a1a",
				"--color-primary-rgb": "26, 26, 26",
				"--color-primary-strong": "#333333",
				"--color-primary-dark": "#1a1a1a",
				"--color-primary-light": "#b1b0b0",
				"--color-primary-light-dark": "#d2d2cf",
				"--color-primary-lighter": "#d8d5cf",
				"--color-primary-bg": "#f5f3f1",
				"--color-primary-bg-light": "#ffffff",
				"--color-accent": "#f5f3f1",
				"--color-accent-rgb": "245, 243, 241",
				"--color-accent-light": "#e5e5e5",
				"--color-bg-primary": "#fdfcfc",
				"--color-bg-secondary": "#ffffff",
				"--color-bg-primary-light": "#f5f3f1",
				"--color-bg-primary-deep": "#fbfaf8",
				"--color-bg-primary-dark": "#11110f",
				"--color-bg-secondary-dark": "#1a1917",
				"--color-text-primary": "#1a1a1a",
				"--color-text-secondary": "#57534f",
				"--color-text-tertiary": "#777169",
				"--color-text-primary-dark": "#f4f4f2",
				"--color-text-secondary-dark": "#d8d5cf",
				"--color-text-tertiary-dark": "#aaa49b",
				"--color-btn-primary": "#1a1a1a",
				"--color-btn-primary-hover": "#333333",
				"--color-btn-primary-dark": "#f4f4f2",
				"--color-btn-primary-dark-hover": "#ffffff",
				"--color-btn-primary-text": "#ffffff",
			},
			dark: {
				"--color-primary": "#f4f4f2",
				"--color-primary-rgb": "244, 244, 242",
				"--color-primary-strong": "#ffffff",
				"--color-primary-light": "#d2d2cf",
				"--color-primary-dark": "#f4f4f2",
				"--color-primary-light-dark": "#f4f4f2",
				"--color-primary-lighter": "#d8d5cf",
				"--color-primary-bg": "rgba(244, 244, 242, 0.12)",
				"--color-primary-bg-light": "rgba(244, 244, 242, 0.06)",
				"--color-accent": "#2a2927",
				"--color-accent-rgb": "42, 41, 39",
				"--color-accent-light": "#363532",
				"--color-bg-primary": "#11110f",
				"--color-bg-secondary": "#1a1917",
				"--color-bg-primary-light": "#151411",
				"--color-bg-primary-deep": "#0d0d0c",
				"--color-bg-primary-dark": "#11110f",
				"--color-bg-secondary-dark": "#1a1917",
				"--color-text-primary": "#f4f4f2",
				"--color-text-secondary": "#d8d5cf",
				"--color-text-tertiary": "#aaa49b",
				"--color-text-primary-dark": "#f4f4f2",
				"--color-text-secondary-dark": "#d8d5cf",
				"--color-text-tertiary-dark": "#aaa49b",
				"--color-btn-primary": "#f4f4f2",
				"--color-btn-primary-hover": "#ffffff",
				"--color-btn-primary-dark": "#f4f4f2",
				"--color-btn-primary-dark-hover": "#ffffff",
				"--color-btn-primary-text": "#11110f",
			},
		},
	},
	{
		id: "forest-green",
		name: "Forest Green",
		description:
			"A quiet green theme with ink text, paper surfaces, and a grounded botanical accent.",
		source: "Botanical palette",
		designDoc: "docs/DESIGN/forest-green.md",
		details: {
			atmosphere:
				"Grounded botanical palette with paper surfaces, natural greens, and low-glare reading contrast.",
			bestFor: ["Knowledge bases", "Wellness products", "Calm product sites"],
			colorRoles: [
				{ name: "Forest Green", value: "#4a7c59", role: "Brand color, links, and filled actions" },
				{ name: "Leaf Tint", value: "#dce9d8", role: "Badges and soft highlights" },
				{ name: "Paper", value: "#f7f5f0", role: "Light page canvas" },
			],
			guidance: [
				"Keep green as the only meaningful chromatic direction.",
				"Use the lighter green tint for supporting surfaces, not primary text.",
				"Make both light and dark variants feel natural and low glare.",
			],
		},
		swatches: ["#4a7c59", "#6f9f7a", "#f5f2ee", "#ffffff", "#121212"],
		lightSwatches: ["#4a7c59", "#356644", "#8fba98", "#dce9d8", "#f7f5f0", "#ffffff"],
		darkSwatches: ["#91c89d", "#b8ddb8", "#cfe8d1", "#263e2d", "#0f1712", "#162119"],
		tokens: {
			light: {
				"--color-primary": "#4a7c59",
				"--color-primary-rgb": "74, 124, 89",
				"--color-primary-strong": "#356644",
				"--color-primary-dark": "#4a7c59",
				"--color-primary-light": "#8fba98",
				"--color-primary-light-dark": "#cfe8d1",
				"--color-primary-lighter": "#b8ddb8",
				"--color-primary-bg": "#eef5ea",
				"--color-primary-bg-light": "#f7f5f0",
				"--color-accent": "#dce9d8",
				"--color-accent-rgb": "220, 233, 216",
				"--color-accent-light": "#edf6e9",
				"--color-bg-primary": "#f7f5f0",
				"--color-bg-secondary": "#ffffff",
				"--color-bg-primary-light": "#f5f2ee",
				"--color-bg-primary-deep": "#fbfaf6",
				"--color-bg-primary-dark": "#0f1712",
				"--color-bg-secondary-dark": "#162119",
				"--color-text-primary": "#2f6840",
				"--color-text-secondary": "#33443a",
				"--color-text-tertiary": "#66736a",
				"--color-text-primary-dark": "#91c89d",
				"--color-text-secondary-dark": "#d5ded7",
				"--color-text-tertiary-dark": "#9daf9f",
				"--color-btn-primary": "#4a7c59",
				"--color-btn-primary-hover": "#356644",
				"--color-btn-primary-dark": "#6f9f7a",
				"--color-btn-primary-dark-hover": "#91c89d",
				"--color-btn-primary-text": "#ffffff",
			},
			dark: {
				"--color-primary": "#91c89d",
				"--color-primary-rgb": "145, 200, 157",
				"--color-primary-strong": "#b8ddb8",
				"--color-primary-light": "#cfe8d1",
				"--color-primary-dark": "#91c89d",
				"--color-primary-light-dark": "#91c89d",
				"--color-primary-lighter": "#b8ddb8",
				"--color-primary-bg": "rgba(145, 200, 157, 0.15)",
				"--color-primary-bg-light": "rgba(145, 200, 157, 0.06)",
				"--color-accent": "#263e2d",
				"--color-accent-rgb": "38, 62, 45",
				"--color-accent-light": "#31523a",
				"--color-bg-primary": "#0f1712",
				"--color-bg-secondary": "#162119",
				"--color-bg-primary-light": "#111c15",
				"--color-bg-primary-deep": "#0a120d",
				"--color-bg-primary-dark": "#0f1712",
				"--color-bg-secondary-dark": "#162119",
				"--color-text-primary": "#91c89d",
				"--color-text-secondary": "#d5ded7",
				"--color-text-tertiary": "#9daf9f",
				"--color-text-primary-dark": "#91c89d",
				"--color-text-secondary-dark": "#d5ded7",
				"--color-text-tertiary-dark": "#9daf9f",
				"--color-btn-primary": "#91c89d",
				"--color-btn-primary-hover": "#b8ddb8",
				"--color-btn-primary-dark": "#91c89d",
				"--color-btn-primary-dark-hover": "#b8ddb8",
				"--color-btn-primary-text": "#0f1712",
			},
		},
	},
	{
		id: "vellum-ink",
		name: "Vellum Ink",
		description:
			"A warm vellum theme with creamy paper, articulate ink, restrained borders, and a small terra cotta accent.",
		source: "Warm vellum palette",
		designDoc: "docs/DESIGN/vellum-ink.md",
		details: {
			atmosphere:
				"Academic journal on vellum: warm off-white surfaces, precise dark text, and a quiet terra cotta accent.",
			bestFor: ["AI products", "Research tools", "Writing apps", "Knowledge products"],
			colorRoles: [
				{ name: "Ink Black", value: "#141413", role: "Primary text, headings, and dark filled actions" },
				{ name: "Vellum White", value: "#faf9f5", role: "Page canvas and card surfaces" },
				{ name: "Terra Cotta", value: "#d97757", role: "Small accent moments and icon details" },
			],
			guidance: [
				"Use warm neutral surfaces generously; avoid harsh pure-white layouts.",
				"Keep terra cotta small and intentional so the theme stays understated.",
				"Use dark filled buttons for the clearest primary action.",
			],
		},
		swatches: ["#141413", "#3d3d3a", "#d97757", "#faf9f5", "#dedcd1"],
		lightSwatches: ["#141413", "#1f1e1d", "#3d3d3a", "#d97757", "#faf9f5", "#ffffff"],
		darkSwatches: ["#faf9f5", "#dedcd1", "#d97757", "#2a2925", "#141413", "#1f1e1d"],
		tokens: {
			light: {
				"--color-primary": "#141413",
				"--color-primary-rgb": "20, 20, 19",
				"--color-primary-strong": "#1f1e1d",
				"--color-primary-dark": "#141413",
				"--color-primary-light": "#9c9a92",
				"--color-primary-light-dark": "#dedcd1",
				"--color-primary-lighter": "#dedcd1",
				"--color-primary-bg": "#f1eee7",
				"--color-primary-bg-light": "#faf9f5",
				"--color-accent": "#d97757",
				"--color-accent-rgb": "217, 119, 87",
				"--color-accent-light": "#e7b29d",
				"--color-bg-primary": "#faf9f5",
				"--color-bg-secondary": "#ffffff",
				"--color-bg-primary-light": "#f4f1ea",
				"--color-bg-primary-deep": "#fffdf7",
				"--color-bg-primary-dark": "#141413",
				"--color-bg-secondary-dark": "#1f1e1d",
				"--color-text-primary": "#141413",
				"--color-text-secondary": "#3d3d3a",
				"--color-text-tertiary": "#73726c",
				"--color-text-primary-dark": "#faf9f5",
				"--color-text-secondary-dark": "#dedcd1",
				"--color-text-tertiary-dark": "#9c9a92",
				"--color-btn-primary": "#141413",
				"--color-btn-primary-hover": "#1f1e1d",
				"--color-btn-primary-dark": "#faf9f5",
				"--color-btn-primary-dark-hover": "#ffffff",
				"--color-btn-primary-text": "#ffffff",
			},
			dark: {
				"--color-primary": "#faf9f5",
				"--color-primary-rgb": "250, 249, 245",
				"--color-primary-strong": "#ffffff",
				"--color-primary-light": "#dedcd1",
				"--color-primary-dark": "#faf9f5",
				"--color-primary-light-dark": "#faf9f5",
				"--color-primary-lighter": "#dedcd1",
				"--color-primary-bg": "rgba(250, 249, 245, 0.12)",
				"--color-primary-bg-light": "rgba(250, 249, 245, 0.06)",
				"--color-accent": "#d97757",
				"--color-accent-rgb": "217, 119, 87",
				"--color-accent-light": "#e7b29d",
				"--color-bg-primary": "#141413",
				"--color-bg-secondary": "#1f1e1d",
				"--color-bg-primary-light": "#191816",
				"--color-bg-primary-deep": "#0f0f0e",
				"--color-bg-primary-dark": "#141413",
				"--color-bg-secondary-dark": "#1f1e1d",
				"--color-text-primary": "#faf9f5",
				"--color-text-secondary": "#dedcd1",
				"--color-text-tertiary": "#9c9a92",
				"--color-text-primary-dark": "#faf9f5",
				"--color-text-secondary-dark": "#dedcd1",
				"--color-text-tertiary-dark": "#9c9a92",
				"--color-btn-primary": "#faf9f5",
				"--color-btn-primary-hover": "#ffffff",
				"--color-btn-primary-dark": "#faf9f5",
				"--color-btn-primary-dark-hover": "#ffffff",
				"--color-btn-primary-text": "#141413",
			},
		},
	},
	{
		id: "creator-yellow",
		name: "Creator Yellow",
		description:
			"A friendly creator economy palette with soft gray canvas, white cards, black text, and bright yellow action.",
		source: "Creator economy palette",
		designDoc: "docs/DESIGN/creator-yellow.md",
		details: {
			atmosphere:
				"Buoyant community canvas with tactile white cards, soft shadows, bright yellow action, and approachable dark text.",
			bestFor: ["Creator tools", "Community sites", "Support pages", "Commerce landing pages"],
			colorRoles: [
				{ name: "Goldenrod", value: "#ffdd00", role: "Primary action and brand highlight" },
				{ name: "Deep Graphite", value: "#222222", role: "Headings and strong body text" },
				{ name: "Canvas Gray", value: "#e5e7eb", role: "Soft page background" },
			],
			guidance: [
				"Let yellow own the main action; avoid adding competing saturated accents.",
				"Use white cards over the gray canvas to preserve the creator-card feeling.",
				"Pair yellow with black text for crisp, friendly contrast.",
			],
		},
		swatches: ["#ffdd00", "#f7d046", "#d8573f", "#ffffff", "#222222"],
		lightSwatches: ["#ffdd00", "#f7d046", "#d8573f", "#e5e7eb", "#ffffff", "#222222"],
		darkSwatches: ["#ffdd00", "#f7d046", "#d8573f", "#2a2614", "#171510", "#222222"],
		tokens: {
			light: {
				"--color-primary": "#222222",
				"--color-primary-rgb": "34, 34, 34",
				"--color-primary-strong": "#000000",
				"--color-primary-dark": "#222222",
				"--color-primary-light": "#717171",
				"--color-primary-light-dark": "#ffdd00",
				"--color-primary-lighter": "#f7d046",
				"--color-primary-bg": "#fff6b8",
				"--color-primary-bg-light": "#ffffff",
				"--color-accent": "#ffdd00",
				"--color-accent-rgb": "255, 221, 0",
				"--color-accent-light": "#f7d046",
				"--color-bg-primary": "#e5e7eb",
				"--color-bg-secondary": "#ffffff",
				"--color-bg-primary-light": "#f3f4f6",
				"--color-bg-primary-deep": "#fafafa",
				"--color-bg-primary-dark": "#171510",
				"--color-bg-secondary-dark": "#222222",
				"--color-text-primary": "#222222",
				"--color-text-secondary": "#414141",
				"--color-text-tertiary": "#717171",
				"--color-text-primary-dark": "#fff8d1",
				"--color-text-secondary-dark": "#f5f0c4",
				"--color-text-tertiary-dark": "#c7bd78",
				"--color-btn-primary": "#ffdd00",
				"--color-btn-primary-hover": "#f7d046",
				"--color-btn-primary-dark": "#ffdd00",
				"--color-btn-primary-dark-hover": "#f7d046",
				"--color-btn-primary-text": "#000000",
			},
			dark: {
				"--color-primary": "#ffdd00",
				"--color-primary-rgb": "255, 221, 0",
				"--color-primary-strong": "#f7d046",
				"--color-primary-light": "#fff2a6",
				"--color-primary-dark": "#ffdd00",
				"--color-primary-light-dark": "#ffdd00",
				"--color-primary-lighter": "#fff2a6",
				"--color-primary-bg": "rgba(255, 221, 0, 0.15)",
				"--color-primary-bg-light": "rgba(255, 221, 0, 0.07)",
				"--color-accent": "#d8573f",
				"--color-accent-rgb": "216, 87, 63",
				"--color-accent-light": "#f5d5cf",
				"--color-bg-primary": "#171510",
				"--color-bg-secondary": "#222222",
				"--color-bg-primary-light": "#1f1c13",
				"--color-bg-primary-deep": "#100f0b",
				"--color-bg-primary-dark": "#171510",
				"--color-bg-secondary-dark": "#222222",
				"--color-text-primary": "#fff8d1",
				"--color-text-secondary": "#f5f0c4",
				"--color-text-tertiary": "#c7bd78",
				"--color-text-primary-dark": "#fff8d1",
				"--color-text-secondary-dark": "#f5f0c4",
				"--color-text-tertiary-dark": "#c7bd78",
				"--color-btn-primary": "#ffdd00",
				"--color-btn-primary-hover": "#f7d046",
				"--color-btn-primary-dark": "#ffdd00",
				"--color-btn-primary-dark-hover": "#f7d046",
				"--color-btn-primary-text": "#000000",
			},
		},
	},
	{
		id: "precision-orange",
		name: "Precision Orange",
		description:
			"A technical neutral theme with stark gray surfaces, black text, and one precise orange signal.",
		source: "Technical neutral palette",
		designDoc: "docs/DESIGN/precision-orange.md",
		details: {
			atmosphere:
				"Technical brutalism with monochrome structure, compressed engineering clarity, and a single orange indicator.",
			bestFor: ["Developer tools", "CLI products", "AI engineering platforms", "Technical docs"],
			colorRoles: [
				{ name: "Factory Black", value: "#020202", role: "Primary text and stark interactive contrast" },
				{ name: "Factory Light Gray", value: "#eeeeee", role: "Page canvas and quiet surfaces" },
				{ name: "Code Orange", value: "#ef6f2e", role: "Status labels and small high-attention signals" },
			],
			guidance: [
				"Use orange sparingly for new, active, or technical signal states.",
				"Lean on black, gray, and spacing for hierarchy rather than decoration.",
				"Keep the palette crisp and utilitarian.",
			],
		},
		swatches: ["#020202", "#3d3a39", "#ef6f2e", "#eeeeee", "#fafafa"],
		lightSwatches: ["#020202", "#3d3a39", "#b8b3b0", "#ef6f2e", "#eeeeee", "#fafafa"],
		darkSwatches: ["#ff9a62", "#f2e8e2", "#d8cbc3", "#2a2623", "#101010", "#1a1817"],
		tokens: {
			light: {
				"--color-primary": "#020202",
				"--color-primary-rgb": "2, 2, 2",
				"--color-primary-strong": "#3d3a39",
				"--color-primary-dark": "#020202",
				"--color-primary-light": "#b8b3b0",
				"--color-primary-light-dark": "#ff9a62",
				"--color-primary-lighter": "#d8d5d2",
				"--color-primary-bg": "#e6e4e2",
				"--color-primary-bg-light": "#fafafa",
				"--color-accent": "#ef6f2e",
				"--color-accent-rgb": "239, 111, 46",
				"--color-accent-light": "#ffb08a",
				"--color-bg-primary": "#eeeeee",
				"--color-bg-secondary": "#fafafa",
				"--color-bg-primary-light": "#f4f4f4",
				"--color-bg-primary-deep": "#ffffff",
				"--color-bg-primary-dark": "#101010",
				"--color-bg-secondary-dark": "#1a1817",
				"--color-text-primary": "#020202",
				"--color-text-secondary": "#3d3a39",
				"--color-text-tertiary": "#756f6b",
				"--color-text-primary-dark": "#f2e8e2",
				"--color-text-secondary-dark": "#d8cbc3",
				"--color-text-tertiary-dark": "#a49d9a",
				"--color-btn-primary": "#020202",
				"--color-btn-primary-hover": "#3d3a39",
				"--color-btn-primary-dark": "#ff9a62",
				"--color-btn-primary-dark-hover": "#ffb08a",
				"--color-btn-primary-text": "#ffffff",
			},
			dark: {
				"--color-primary": "#ff9a62",
				"--color-primary-rgb": "255, 154, 98",
				"--color-primary-strong": "#ffb08a",
				"--color-primary-light": "#ffd2bd",
				"--color-primary-dark": "#ff9a62",
				"--color-primary-light-dark": "#ff9a62",
				"--color-primary-lighter": "#ffd2bd",
				"--color-primary-bg": "rgba(255, 154, 98, 0.15)",
				"--color-primary-bg-light": "rgba(255, 154, 98, 0.07)",
				"--color-accent": "#ef6f2e",
				"--color-accent-rgb": "239, 111, 46",
				"--color-accent-light": "#ffb08a",
				"--color-bg-primary": "#101010",
				"--color-bg-secondary": "#1a1817",
				"--color-bg-primary-light": "#171615",
				"--color-bg-primary-deep": "#090909",
				"--color-bg-primary-dark": "#101010",
				"--color-bg-secondary-dark": "#1a1817",
				"--color-text-primary": "#f2e8e2",
				"--color-text-secondary": "#d8cbc3",
				"--color-text-tertiary": "#a49d9a",
				"--color-text-primary-dark": "#f2e8e2",
				"--color-text-secondary-dark": "#d8cbc3",
				"--color-text-tertiary-dark": "#a49d9a",
				"--color-btn-primary": "#ff9a62",
				"--color-btn-primary-hover": "#ffb08a",
				"--color-btn-primary-dark": "#ff9a62",
				"--color-btn-primary-dark-hover": "#ffb08a",
				"--color-btn-primary-text": "#101010",
			},
		},
	},
	{
		id: "comic-pulp",
		name: "Comic Pulp",
		description:
			"A soft pulp comic palette with pale paper backgrounds, grape-lavender structure, lemon yellow action, and graphic ink contrast.",
		source: "Soft comic palette",
		designDoc: "docs/DESIGN/comic-pulp.md",
		details: {
			atmosphere:
				"Soft pulp comic energy: pale paper canvas first, grape-lavender structure second, lemon-yellow action, and graphic ink contrast.",
			bestFor: ["Playful brands", "Campaign pages", "Games", "Creative launches"],
			colorRoles: [
				{ name: "Grape Ink", value: "#6b5fb5", role: "Headings, links, and brand structure" },
				{ name: "Lemon Drop", value: "#f2dc4d", role: "Primary action and cheerful emphasis" },
				{ name: "Pulp Paper", value: "#fbf7ea", role: "Soft page background" },
			],
			guidance: [
				"Keep the page background pale so the comic accents have room to breathe.",
				"Use yellow for action and emphasis, balanced by grape text instead of pure black everywhere.",
				"Let the theme feel graphic through color contrast without turning the whole page saturated.",
			],
		},
		swatches: ["#6b5fb5", "#c8c1f0", "#f2dc4d", "#fbf7ea", "#241c3d"],
		lightSwatches: ["#6b5fb5", "#3f357d", "#c8c1f0", "#f2dc4d", "#fbf7ea", "#fffdf5"],
		darkSwatches: ["#f2dc4d", "#c8c1f0", "#f6cc5f", "#3f357d", "#18152d", "#252040"],
		tokens: {
			light: {
				"--color-primary": "#6b5fb5",
				"--color-primary-rgb": "107, 95, 181",
				"--color-primary-strong": "#3f357d",
				"--color-primary-dark": "#6b5fb5",
				"--color-primary-light": "#c8c1f0",
				"--color-primary-light-dark": "#f2dc4d",
				"--color-primary-lighter": "#e8e4ff",
				"--color-primary-bg": "#eeeaff",
				"--color-primary-bg-light": "#fffdf5",
				"--color-accent": "#f2dc4d",
				"--color-accent-rgb": "242, 220, 77",
				"--color-accent-light": "#f6cc5f",
				"--color-bg-primary": "#fbf7ea",
				"--color-bg-secondary": "#fffdf5",
				"--color-bg-primary-light": "#f4efff",
				"--color-bg-primary-deep": "#fffaf0",
				"--color-bg-primary-dark": "#18152d",
				"--color-bg-secondary-dark": "#252040",
				"--color-text-primary": "#241c3d",
				"--color-text-secondary": "#473f67",
				"--color-text-tertiary": "#806f4b",
				"--color-text-primary-dark": "#f2dc4d",
				"--color-text-secondary-dark": "#f6f0d1",
				"--color-text-tertiary-dark": "#c8c1f0",
				"--color-btn-primary": "#f2dc4d",
				"--color-btn-primary-hover": "#f6cc5f",
				"--color-btn-primary-dark": "#f2dc4d",
				"--color-btn-primary-dark-hover": "#f6cc5f",
				"--color-btn-primary-text": "#241c3d",
			},
			dark: {
				"--color-primary": "#f2dc4d",
				"--color-primary-rgb": "242, 220, 77",
				"--color-primary-strong": "#f6cc5f",
				"--color-primary-light": "#fff2a6",
				"--color-primary-dark": "#f2dc4d",
				"--color-primary-light-dark": "#f2dc4d",
				"--color-primary-lighter": "#fff2a6",
				"--color-primary-bg": "rgba(242, 220, 77, 0.16)",
				"--color-primary-bg-light": "rgba(242, 220, 77, 0.08)",
				"--color-accent": "#c8c1f0",
				"--color-accent-rgb": "200, 193, 240",
				"--color-accent-light": "#e8e4ff",
				"--color-bg-primary": "#18152d",
				"--color-bg-secondary": "#252040",
				"--color-bg-primary-light": "#211c3a",
				"--color-bg-primary-deep": "#100e20",
				"--color-bg-primary-dark": "#18152d",
				"--color-bg-secondary-dark": "#252040",
				"--color-text-primary": "#f2dc4d",
				"--color-text-secondary": "#f6f0d1",
				"--color-text-tertiary": "#c8c1f0",
				"--color-text-primary-dark": "#f2dc4d",
				"--color-text-secondary-dark": "#f6f0d1",
				"--color-text-tertiary-dark": "#c8c1f0",
				"--color-btn-primary": "#f2dc4d",
				"--color-btn-primary-hover": "#f6cc5f",
				"--color-btn-primary-dark": "#f2dc4d",
				"--color-btn-primary-dark-hover": "#f6cc5f",
				"--color-btn-primary-text": "#241c3d",
			},
		},
	},
	{
		id: "midnight-pastel",
		name: "Midnight Pastel",
		description:
			"A dark collaborative palette with black canvas, muted pastel cards, violet accents, and warm clay actions.",
		source: "Dark pastel palette",
		designDoc: "docs/DESIGN/midnight-pastel.md",
		details: {
			atmosphere:
				"Matte pastel blocks on midnight: a dark workspace softened by violet, ochre, rose, and clay accents.",
			bestFor: ["Creative workspaces", "Collaboration tools", "Project dashboards", "Studios"],
			colorRoles: [
				{ name: "Midnight Canvas", value: "#000000", role: "Dark page foundation" },
				{ name: "Warm Violet", value: "#bbb2ce", role: "Prominent accent and project-card energy" },
				{ name: "Earth Clay", value: "#65451d", role: "Grounded primary action color" },
			],
			guidance: [
				"Let the dark base carry the interface, then use pastels as controlled highlights.",
				"Use clay and ochre for warm actions rather than generic bright colors.",
				"Avoid sharp neon colors; keep the palette muted and tactile.",
			],
		},
		swatches: ["#000000", "#bbb2ce", "#e4b976", "#65451d", "#cb9da2"],
		lightSwatches: ["#453b60", "#bbb2ce", "#e4b976", "#65451d", "#f3f1ec", "#ffffff"],
		darkSwatches: ["#bbb2ce", "#e4b976", "#cb9da2", "#65451d", "#000000", "#121212"],
		tokens: {
			light: {
				"--color-primary": "#453b60",
				"--color-primary-rgb": "69, 59, 96",
				"--color-primary-strong": "#65451d",
				"--color-primary-dark": "#453b60",
				"--color-primary-light": "#bbb2ce",
				"--color-primary-light-dark": "#bbb2ce",
				"--color-primary-lighter": "#d9d2e7",
				"--color-primary-bg": "#ebe7f3",
				"--color-primary-bg-light": "#f3f1ec",
				"--color-accent": "#e4b976",
				"--color-accent-rgb": "228, 185, 118",
				"--color-accent-light": "#f0d6a8",
				"--color-bg-primary": "#f3f1ec",
				"--color-bg-secondary": "#ffffff",
				"--color-bg-primary-light": "#e5e6e1",
				"--color-bg-primary-deep": "#fbfaf6",
				"--color-bg-primary-dark": "#000000",
				"--color-bg-secondary-dark": "#121212",
				"--color-text-primary": "#453b60",
				"--color-text-secondary": "#333333",
				"--color-text-tertiary": "#65451d",
				"--color-text-primary-dark": "#bbb2ce",
				"--color-text-secondary-dark": "#ffffff",
				"--color-text-tertiary-dark": "#e4b976",
				"--color-btn-primary": "#65451d",
				"--color-btn-primary-hover": "#453b60",
				"--color-btn-primary-dark": "#bbb2ce",
				"--color-btn-primary-dark-hover": "#e4b976",
				"--color-btn-primary-text": "#ffffff",
			},
			dark: {
				"--color-primary": "#bbb2ce",
				"--color-primary-rgb": "187, 178, 206",
				"--color-primary-strong": "#e4b976",
				"--color-primary-light": "#d9d2e7",
				"--color-primary-dark": "#bbb2ce",
				"--color-primary-light-dark": "#bbb2ce",
				"--color-primary-lighter": "#d9d2e7",
				"--color-primary-bg": "rgba(187, 178, 206, 0.16)",
				"--color-primary-bg-light": "rgba(187, 178, 206, 0.08)",
				"--color-accent": "#e4b976",
				"--color-accent-rgb": "228, 185, 118",
				"--color-accent-light": "#f0d6a8",
				"--color-bg-primary": "#000000",
				"--color-bg-secondary": "#121212",
				"--color-bg-primary-light": "#0b0b0b",
				"--color-bg-primary-deep": "#000000",
				"--color-bg-primary-dark": "#000000",
				"--color-bg-secondary-dark": "#121212",
				"--color-text-primary": "#bbb2ce",
				"--color-text-secondary": "#ffffff",
				"--color-text-tertiary": "#e4b976",
				"--color-text-primary-dark": "#bbb2ce",
				"--color-text-secondary-dark": "#ffffff",
				"--color-text-tertiary-dark": "#e4b976",
				"--color-btn-primary": "#bbb2ce",
				"--color-btn-primary-hover": "#e4b976",
				"--color-btn-primary-dark": "#bbb2ce",
				"--color-btn-primary-dark-hover": "#e4b976",
				"--color-btn-primary-text": "#000000",
			},
		},
	},
	{
		id: "sky-blue",
		name: "Sky Blue",
		description:
			"A pale blue-white product palette with near-white canvas, sky wash surfaces, midnight ink, and vivid blue focus.",
		source: "Pale product palette",
		designDoc: "docs/DESIGN/sky-blue.md",
		details: {
			atmosphere:
				"Blueprint on frosted linen with a near-white base, soft sky-blue wash, and vivid blue used like a highlighter.",
			bestFor: ["CRM products", "SaaS dashboards", "Pipeline tools", "Productivity apps"],
			colorRoles: [
				{ name: "Signal Blue", value: "#145aff", role: "Links, focus rings, and high-emphasis action" },
				{ name: "Linen Canvas", value: "#fcfcfc", role: "Primary page surface" },
				{ name: "Midnight Ink", value: "#020520", role: "Dense display text and strong controls" },
			],
			guidance: [
				"Use blue as a precise signal, not as an all-over paint color.",
				"Let near-white and pale sky surfaces provide most of the depth.",
				"Keep secondary text in blue-gray neutrals for a calm product feel.",
			],
		},
		swatches: ["#145aff", "#b6cbfd", "#f0f4fe", "#fcfcfc", "#020520"],
		lightSwatches: ["#145aff", "#0f1f3d", "#b6cbfd", "#f0f4fe", "#fcfcfc", "#ffffff"],
		darkSwatches: ["#83a6ff", "#b6cbfd", "#f0f4fe", "#17254a", "#080b1a", "#11182f"],
		tokens: {
			light: {
				"--color-primary": "#145aff",
				"--color-primary-rgb": "20, 90, 255",
				"--color-primary-strong": "#0f1f3d",
				"--color-primary-dark": "#145aff",
				"--color-primary-light": "#b6cbfd",
				"--color-primary-light-dark": "#83a6ff",
				"--color-primary-lighter": "#dbe6ff",
				"--color-primary-bg": "#f0f4fe",
				"--color-primary-bg-light": "#fcfcfc",
				"--color-accent": "#f0f4fe",
				"--color-accent-rgb": "240, 244, 254",
				"--color-accent-light": "#b6cbfd",
				"--color-bg-primary": "#fcfcfc",
				"--color-bg-secondary": "#ffffff",
				"--color-bg-primary-light": "#f0f4fe",
				"--color-bg-primary-deep": "#ffffff",
				"--color-bg-primary-dark": "#080b1a",
				"--color-bg-secondary-dark": "#11182f",
				"--color-text-primary": "#020520",
				"--color-text-secondary": "#374151",
				"--color-text-tertiary": "#696a72",
				"--color-text-primary-dark": "#83a6ff",
				"--color-text-secondary-dark": "#dbe6ff",
				"--color-text-tertiary-dark": "#9dadcf",
				"--color-btn-primary": "#145aff",
				"--color-btn-primary-hover": "#0f1f3d",
				"--color-btn-primary-dark": "#83a6ff",
				"--color-btn-primary-dark-hover": "#b6cbfd",
				"--color-btn-primary-text": "#ffffff",
			},
			dark: {
				"--color-primary": "#83a6ff",
				"--color-primary-rgb": "131, 166, 255",
				"--color-primary-strong": "#b6cbfd",
				"--color-primary-light": "#dbe6ff",
				"--color-primary-dark": "#83a6ff",
				"--color-primary-light-dark": "#83a6ff",
				"--color-primary-lighter": "#dbe6ff",
				"--color-primary-bg": "rgba(131, 166, 255, 0.16)",
				"--color-primary-bg-light": "rgba(131, 166, 255, 0.07)",
				"--color-accent": "#17254a",
				"--color-accent-rgb": "23, 37, 74",
				"--color-accent-light": "#24396e",
				"--color-bg-primary": "#080b1a",
				"--color-bg-secondary": "#11182f",
				"--color-bg-primary-light": "#0c1225",
				"--color-bg-primary-deep": "#050714",
				"--color-bg-primary-dark": "#080b1a",
				"--color-bg-secondary-dark": "#11182f",
				"--color-text-primary": "#83a6ff",
				"--color-text-secondary": "#dbe6ff",
				"--color-text-tertiary": "#9dadcf",
				"--color-text-primary-dark": "#83a6ff",
				"--color-text-secondary-dark": "#dbe6ff",
				"--color-text-tertiary-dark": "#9dadcf",
				"--color-btn-primary": "#83a6ff",
				"--color-btn-primary-hover": "#b6cbfd",
				"--color-btn-primary-dark": "#83a6ff",
				"--color-btn-primary-dark-hover": "#b6cbfd",
				"--color-btn-primary-text": "#080b1a",
			},
		},
	},
	{
		id: "signal-red",
		name: "Signal Red",
		description:
			"A pragmatic red-accent theme with warm gray-white canvas, strong graphite text, and confident red action.",
		source: "Red action palette",
		designDoc: "docs/DESIGN/signal-red.md",
		details: {
			atmosphere:
				"Cloud control panel on pristine paper: enterprise clarity, warm grays, strong typography, and one confident red action color.",
			bestFor: ["B2B SaaS", "Infrastructure tools", "Security products", "Enterprise docs"],
			colorRoles: [
				{ name: "Action Red", value: "#d04841", role: "Primary calls to action and active states" },
				{ name: "Graphite Black", value: "#181717", role: "Headings and strong text" },
				{ name: "Canvas Pale", value: "#eeebea", role: "Warm page background" },
			],
			guidance: [
				"Reserve red for primary action or unambiguous active state.",
				"Use warm gray surfaces to soften the enterprise palette.",
				"Prefer strong text contrast and simple card surfaces over decoration.",
			],
		},
		swatches: ["#d04841", "#181717", "#2e2d2d", "#eeebea", "#ffffff"],
		lightSwatches: ["#d04841", "#a83b35", "#181717", "#d5d3d2", "#eeebea", "#ffffff"],
		darkSwatches: ["#ff867f", "#f7f2ef", "#e7e1df", "#3a3635", "#181717", "#2e2d2d"],
		tokens: {
			light: {
				"--color-primary": "#d04841",
				"--color-primary-rgb": "208, 72, 65",
				"--color-primary-strong": "#a83b35",
				"--color-primary-dark": "#d04841",
				"--color-primary-light": "#f2aaa5",
				"--color-primary-light-dark": "#ff867f",
				"--color-primary-lighter": "#f9d4d1",
				"--color-primary-bg": "#f8e6e4",
				"--color-primary-bg-light": "#ffffff",
				"--color-accent": "#eeebea",
				"--color-accent-rgb": "238, 235, 234",
				"--color-accent-light": "#f7f5f4",
				"--color-bg-primary": "#eeebea",
				"--color-bg-secondary": "#ffffff",
				"--color-bg-primary-light": "#f7f5f4",
				"--color-bg-primary-deep": "#ffffff",
				"--color-bg-primary-dark": "#181717",
				"--color-bg-secondary-dark": "#2e2d2d",
				"--color-text-primary": "#181717",
				"--color-text-secondary": "#2e2d2d",
				"--color-text-tertiary": "#706e6d",
				"--color-text-primary-dark": "#f7f2ef",
				"--color-text-secondary-dark": "#e7e1df",
				"--color-text-tertiary-dark": "#b7b1af",
				"--color-btn-primary": "#d04841",
				"--color-btn-primary-hover": "#a83b35",
				"--color-btn-primary-dark": "#ff867f",
				"--color-btn-primary-dark-hover": "#ffb3ae",
				"--color-btn-primary-text": "#ffffff",
			},
			dark: {
				"--color-primary": "#ff867f",
				"--color-primary-rgb": "255, 134, 127",
				"--color-primary-strong": "#ffb3ae",
				"--color-primary-light": "#ffd8d5",
				"--color-primary-dark": "#ff867f",
				"--color-primary-light-dark": "#ff867f",
				"--color-primary-lighter": "#ffd8d5",
				"--color-primary-bg": "rgba(255, 134, 127, 0.16)",
				"--color-primary-bg-light": "rgba(255, 134, 127, 0.07)",
				"--color-accent": "#3a3635",
				"--color-accent-rgb": "58, 54, 53",
				"--color-accent-light": "#4a4544",
				"--color-bg-primary": "#181717",
				"--color-bg-secondary": "#2e2d2d",
				"--color-bg-primary-light": "#201f1f",
				"--color-bg-primary-deep": "#111010",
				"--color-bg-primary-dark": "#181717",
				"--color-bg-secondary-dark": "#2e2d2d",
				"--color-text-primary": "#f7f2ef",
				"--color-text-secondary": "#e7e1df",
				"--color-text-tertiary": "#b7b1af",
				"--color-text-primary-dark": "#f7f2ef",
				"--color-text-secondary-dark": "#e7e1df",
				"--color-text-tertiary-dark": "#b7b1af",
				"--color-btn-primary": "#ff867f",
				"--color-btn-primary-hover": "#ffb3ae",
				"--color-btn-primary-dark": "#ff867f",
				"--color-btn-primary-dark-hover": "#ffb3ae",
				"--color-btn-primary-text": "#181717",
			},
		},
	},
];

export const themeById = Object.fromEntries(themes.map((theme) => [theme.id, theme]));
